### ISSUE TITLE
[Suggestion] "Player in Game" and "Player not in Game" functions

### ISSUE THREAD

**Issue by Shazuli** [piotrulos/MSCModLoader#24]
***Hi!***

We have `OnLoad()` and `Update()` in the MSCModloader. But it would be good if we had two more of these called `InGame()` and `OutGame()` (or some other name).

```CS
    public override void InGame()
    {
          //ModConsole.Print("The player is now in the game.");
    }

    public override void OutGame()
    {
          //ModConsole.Print("The player is no longer in the game.");
    }
```

Then we do not longer need to check what scene we are in in `Update()`.

```CS

    if (!isModDoneLoading && Application.loadedLevelName == "GAME")
        {
              //Do when player joins the game.
              isModDoneLoading = true;
        }
    
    if (isModDoneLoading && Application.loadedLevelName != "GAME")
        {
              //Do when player is no longer in the game.
              isModDoneLoading = false;
        }
```
You think this could be a thing? I think this would make things easier for modders.

**Comment by piotrulos** [comment]
I think it no longer makes sense, since all mods are now reset when player goes back to main menu. (mods doesn't do anything now in main menu Update is not called)
OnLoad is now called every time when you click "continue" or "new game", because every time you go back to main menu mods are reset to begining state (like you just start game).

There is a flag to set to allow mod load in main menu, but it is unfinished (there will be OnMenuLoad function added).

**Comment by Shazuli** [comment]
Ah, ok. I should have read the changelog more carefully!
