### ISSUE TITLE
Add Event Example

### ISSUE THREAD

**Issue by Najsr** [piotrulos/MSCModLoader#4]
Hello there, could you please add example of using events? 

Thanks :)

**Comment by piotrulos** [comment]
You mean FSMevents?
Just call:
`PlayMakerFSM.BroadcastEvent("EventName");`

Change `EventName` to valid event name, and remember to add `PlayMaker.dll` to references.

**Comment by Najsr** [comment]
I meant how to set handler when event that i subscribe to occurs. (basically how to subscribe to event)

**Comment by piotrulos** [comment]
> I meant how to set handler when event that i subscribe to occurs. (basically how to subscribe to event)
I try to understand what you say, but can't.

Maybe paste a code and what do you want to do with it.

**Comment by Najsr** [comment]
When event occurs I want to run some code. That's all

**Comment by piotrulos** [comment]
I did not find anything about that in playmaker docs. I can't find any way to capture event, only broadcast them, so probably it's not possible.
Playmaker is just a prototyping tool, and shouldn't be used in final product, but unfortunately devs don't care about that.

**Comment by Najsr** [comment]
Well.. if calling event triggers some code then that code would have to implement events :D

**Comment by piotrulos** [comment]
But playmaker is just "graph" language (connecting one piece to another, no coding at all).  
Access from c# is limited, only this functions are public https://hutonggames.fogbugz.com/default.asp?W127 
And for events there is only this https://hutonggames.fogbugz.com/default.asp?W1101 I can't find something like` isTriggered` or `isExecuted`. That's why playmaker is bad in production.
