### ISSUE TITLE
Doesn't work on non-Steam versions

### ISSUE THREAD

**Issue by Eepsquared** [piotrulos/MSCModLoader#66]
#### Info
* OS version/build: Windows 7 64-bit
* MSCLoader version: 0.4.7
* Type of issue: suggestion

#### Description
Doesn't work with non-Steam game version. I don't like Steam running in the background so I use a Steam emulator but MSCLoader just loads steam. I want MSCLoader to use launcher.exe instead of mysummercar.exe to start the game.

**Comment by piotrulos** [comment]
srsly?

**Comment by Eepsquared** [comment]
Yes, "srsly". So what?

**Comment by n0tic** [comment]
You "srsly" waited two weeks before posting that?
I think he made himself very clear when closing AND marking it as "Invalid".

**Comment by Eepsquared** [comment]
What's clear other than his refusal to make it work with non-Steam (or Steam-emulated) versions? Pompous and egotistical...

**Comment by piotrulos** [comment]
Talking with you It's like talking to the flat earther.
Pirate whatever you want, but don't make bs stories, you take now numbers from ass that can be easily check.

**Comment by n0tic** [comment]
Eepsquared, This is exactly how to ask for help. You're right. Because you dont seem pompous and egotistical at all.
Keep talking shit and being an ass.

Honestly, I dont belive your steam is taking ~500MB memory/resources. If it is, you're doing something wrong. I have 13 games installed and started scrolling down on the store page to even get it up and above 300MB... This while having GTA-V Online running.

Let this thread die in piece. I can't speak for piotrulos but I don't think you or this issue is worth the time since this isn't really bug.
