### ISSUE TITLE
Could you make some examples on using the ModUI already? 

### ISSUE THREAD

**Issue by haverdaden** [piotrulos/MSCModLoader#7]
Hey.

So you are working on adding the api to the wiki but I would love to see some fast examples on how to create a box with buttons and stuff already :)

**Comment by piotrulos** [comment]
For now this class is a little chaotic. The best way for creating UI is to create it in unity and then move to code using AddComponent/GetComponent. 
ModUI class just simplify some repeated code, finding main canvas, etc.

I think good example is settings code: https://github.com/piotrulos/MSCModLoader/blob/master/MSCLoader/MSCLoader/ModSettings.cs in CreateSettingsUI() function.

But best way is compare this code with unity, check attached scene file in unity itself. And yes it's more code than OnGUI, that's why I want simplify this by ModUI class.
[test scene.zip](https://github.com/piotrulos/MSCModLoader/files/1066781/test.scene.zip)
